// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/telegram/telegram.go

// Package mock_telegram is a generated GoMock package.
package mock_telegram

import (
	gomock "github.com/golang/mock/gomock"
)

// MockCommandsHandler is a mock of CommandsHandler interface.
type MockCommandsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommandsHandlerMockRecorder
}

// MockCommandsHandlerMockRecorder is the mock recorder for MockCommandsHandler.
type MockCommandsHandlerMockRecorder struct {
	mock *MockCommandsHandler
}

// NewMockCommandsHandler creates a new mock instance.
func NewMockCommandsHandler(ctrl *gomock.Controller) *MockCommandsHandler {
	mock := &MockCommandsHandler{ctrl: ctrl}
	mock.recorder = &MockCommandsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandsHandler) EXPECT() *MockCommandsHandlerMockRecorder {
	return m.recorder
}

// MockQueryHandler is a mock of QueryHandler interface.
type MockQueryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockQueryHandlerMockRecorder
}

// MockQueryHandlerMockRecorder is the mock recorder for MockQueryHandler.
type MockQueryHandlerMockRecorder struct {
	mock *MockQueryHandler
}

// NewMockQueryHandler creates a new mock instance.
func NewMockQueryHandler(ctrl *gomock.Controller) *MockQueryHandler {
	mock := &MockQueryHandler{ctrl: ctrl}
	mock.recorder = &MockQueryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryHandler) EXPECT() *MockQueryHandlerMockRecorder {
	return m.recorder
}

// MockInteractionHandler is a mock of InteractionHandler interface.
type MockInteractionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionHandlerMockRecorder
}

// MockInteractionHandlerMockRecorder is the mock recorder for MockInteractionHandler.
type MockInteractionHandlerMockRecorder struct {
	mock *MockInteractionHandler
}

// NewMockInteractionHandler creates a new mock instance.
func NewMockInteractionHandler(ctrl *gomock.Controller) *MockInteractionHandler {
	mock := &MockInteractionHandler{ctrl: ctrl}
	mock.recorder = &MockInteractionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionHandler) EXPECT() *MockInteractionHandlerMockRecorder {
	return m.recorder
}

// MockNotificationsHandler is a mock of NotificationsHandler interface.
type MockNotificationsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsHandlerMockRecorder
}

// MockNotificationsHandlerMockRecorder is the mock recorder for MockNotificationsHandler.
type MockNotificationsHandlerMockRecorder struct {
	mock *MockNotificationsHandler
}

// NewMockNotificationsHandler creates a new mock instance.
func NewMockNotificationsHandler(ctrl *gomock.Controller) *MockNotificationsHandler {
	mock := &MockNotificationsHandler{ctrl: ctrl}
	mock.recorder = &MockNotificationsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsHandler) EXPECT() *MockNotificationsHandlerMockRecorder {
	return m.recorder
}
