services:
  app:
    build:
      context: ../.
      dockerfile: ./build/app/Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
  adminer:
      image: adminer
      restart: unless-stopped
      ports:
          - "8210:8080"
