// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/arthurshafikov/tg-gladiator/internal/core/models"
	types "github.com/arthurshafikov/tg-gladiator/internal/core/types"
	gomock "github.com/golang/mock/gomock"
)

// MockBaseRepo is a mock of BaseRepo interface.
type MockBaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBaseRepoMockRecorder
}

// MockBaseRepoMockRecorder is the mock recorder for MockBaseRepo.
type MockBaseRepoMockRecorder struct {
	mock *MockBaseRepo
}

// NewMockBaseRepo creates a new mock instance.
func NewMockBaseRepo(ctrl *gomock.Controller) *MockBaseRepo {
	mock := &MockBaseRepo{ctrl: ctrl}
	mock.recorder = &MockBaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseRepo) EXPECT() *MockBaseRepoMockRecorder {
	return m.recorder
}

// WrapInTransaction mocks base method.
func (m *MockBaseRepo) WrapInTransaction(ctx *types.Context, txFunc types.TXFunction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WrapInTransaction", ctx, txFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// WrapInTransaction indicates an expected call of WrapInTransaction.
func (mr *MockBaseRepoMockRecorder) WrapInTransaction(ctx, txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WrapInTransaction", reflect.TypeOf((*MockBaseRepo)(nil).WrapInTransaction), ctx, txFunc)
}

// MockChat is a mock of Chat interface.
type MockChat struct {
	ctrl     *gomock.Controller
	recorder *MockChatMockRecorder
}

// MockChatMockRecorder is the mock recorder for MockChat.
type MockChatMockRecorder struct {
	mock *MockChat
}

// NewMockChat creates a new mock instance.
func NewMockChat(ctrl *gomock.Controller) *MockChat {
	mock := &MockChat{ctrl: ctrl}
	mock.recorder = &MockChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChat) EXPECT() *MockChatMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChat) Create(ctx context.Context, chat models.Chat) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, chat)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChatMockRecorder) Create(ctx, chat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChat)(nil).Create), ctx, chat)
}

// Find mocks base method.
func (m *MockChat) Find(ctx context.Context, id int64) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockChatMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockChat)(nil).Find), ctx, id)
}

// FindBy mocks base method.
func (m *MockChat) FindBy(ctx context.Context, fields *models.Chat) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBy", ctx, fields)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBy indicates an expected call of FindBy.
func (mr *MockChatMockRecorder) FindBy(ctx, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBy", reflect.TypeOf((*MockChat)(nil).FindBy), ctx, fields)
}

// Update mocks base method.
func (m *MockChat) Update(ctx context.Context, chatID int64, fields *models.Chat) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, chatID, fields)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockChatMockRecorder) Update(ctx, chatID, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChat)(nil).Update), ctx, chatID, fields)
}

// UpdateMap mocks base method.
func (m *MockChat) UpdateMap(ctx context.Context, chatID int64, fields map[string]interface{}) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMap", ctx, chatID, fields)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMap indicates an expected call of UpdateMap.
func (mr *MockChatMockRecorder) UpdateMap(ctx, chatID, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMap", reflect.TypeOf((*MockChat)(nil).UpdateMap), ctx, chatID, fields)
}
