-- +goose Up
-- +goose StatementBegin
CREATE TABLE enemies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level INT NOT NULL CHECK (level >= 0),
    name VARCHAR(50) NOT NULL,
    hp INT NOT NULL CHECK (hp >= 0),
    min_attack INT NOT NULL CHECK (min_attack >= 0),
    max_attack INT NOT NULL CHECK (max_attack >= 0),
    defense INT NOT NULL,

    critical_chance_percent INT NOT NULL CHECK (critical_chance_percent >= 0),
    evasion_chance_percent INT NOT NULL CHECK (evasion_chance_percent >= 0),

    boss_type VARCHAR(50) NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE enemies;
-- +goose StatementEnd
