-- +goose Up
-- +goose StatementBegin
CREATE TABLE heroes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    class VARCHAR(20) NOT NULL,
    current_hp BIGINT NOT NULL CHECK (current_hp >= 0),
    current_energy BIGINT NOT NULL CHECK (current_energy >= 0),
    current_gold BIGINT NOT NULL CHECK (current_gold >= 0),
    created_at TIMESTAMP NULL DEFAULT NOW(),

    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE heroes;
-- +goose StatementEnd
