-- +goose Up
-- +goose StatementBegin
CREATE TABLE enemies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level INT NOT NULL CHECK (level >= 0),
    name VARCHAR(50) NOT NULL,
    hp INT NOT NULL CHECK (hp >= 0),
    min_attack INT NOT NULL CHECK (min_attack >= 0),
    max_attack INT NOT NULL CHECK (max_attack >= 0),
    defense INT NOT NULL,

    critical_chance_percent INT NOT NULL CHECK (critical_chance_percent >= 0),
    evasion_chance_percent INT NOT NULL CHECK (evasion_chance_percent >= 0),

    gold_reward_min INT NOT NULL CHECK (gold_reward_min >= 0),
    gold_reward_max INT NOT NULL CHECK (gold_reward_max >= 0),

    xp_reward_min INT NOT NULL CHECK (xp_reward_min >= 0),
    xp_reward_max INT NOT NULL CHECK (xp_reward_max >= 0)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE enemies;
-- +goose StatementEnd
