-- +goose Up
-- +goose StatementBegin
CREATE TABLE hero_shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id BIGINT NOT NULL,
    updates_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NULL DEFAULT NOW(),

    FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE hero_shops;
-- +goose StatementEnd
