-- +goose Up
-- +goose StatementBegin
CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    attack_bonus INT NULL,
    defense_bonus INT NULL,
    critical_chance_percent_bonus INT NULL,
    evasion_percent_bonus INT NULL,
    base_price INT NOT NULL CHECK (base_price >= 0)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE items;
-- +goose StatementEnd
