RU:
  StartSuccess: "Успешный старт!"
  Help: "Помощь"

  DeleteConfirmation: "Удалить"

  OpenedMenu: "Это меню"
  DefaultBackBtn: "Назад"

  MenuItemMyHeroes: "Мои герои"
  MyHeroesList: "Это лист ваших героев"

  MenuItemStartTournamentFight: "Учавствовать в Турнире"
  MenuItemDeleteHero: "❌ Удалить"
  HeroDeleteConfirmationPrompt: "⚠️ Пожалуйста, подтвердите удаление героя %s, для подтверждения отправьте сообщением текст '<code>%s</code>', для отмены нажмите на кнопку Назад."
  HeroDeleteCancelled: "Удаление героя было отменено."
  HeroDeleteSuccessful: "❌ Герой был успешно удалён."

  HeroCreationStart: "➕ Создать"
  HeroCreationSelectClass: "Пожалуйста, выберите класс вашего героя, доступные классы:"
  HeroCreationEnterNamePrompt: "Пожалуйста, введите имя для вашего героя, длинной до 50 символов:"

  HeroCreationSuccess: "Герой был успешно создан!"

  HeroOverview: "Ваш герой:"
  HeroClass: "Класс"
  HeroAttack: "💪 Атака"
  HeroDefense: "🛡 Защита"
  HeroCriticalChancePercent: "💥 Шанс критического урона"
  HeroEvasionChancePercent: "🍀 Шанс уворота"
  HP: "❤️ Здоровье"
  HeroEnergy: "🏃‍♂️ Энергия"
  HeroGold: "💰 Золото"

  HeroName: "Имя"
  HeroNameWithStats: "%s - ❤️ %v, 💰 %v"

  FightOverview: "⚔️ Битва ⚔️"
  FightChooseAction: "Выберите действие:"
  FightActionPunch: "👊 Ударить"
  FightActionRunAway: "🏃 Убежать"
  FightRunAwaySuccess: "Вы успешно сбежали 🏃"
  
  FightTurnOverview: "Ход боя"
  FightActionInfoDealtSimplePunch: "Нанёс простым ударом %v урона"
  FightActionInfoDealtSimpleAttack: "Нанёс %v урона"
  FightActionInfoCritical: "крит 💥"
  FightActionInfoOpponentHPLost: "и %s потерял %v ❤️"
  FightActionInfoOpponentEvaded: "и %s увернулся 🍀 (шанс уворота - %v%%)"

  FightResultHeroWon: "Поздравляем, вы победили!"
  FightResultOpponentWon: "К сожалению вы проиграли"

  HeroClasses:
    swordsman: "⚔️ Мечник"

  Errors:
    403_forbidden: "⛔️ Ошибка: недостаточно прав для выполнения действия"
    404_not_found: "🔍 Ошибка: не найдено"
    500_server_error: "⚠️ Ошибка: проблемы на сервере, попробуйте позже"
    429_too_many_requests: "🚫 Ошибка: слишком много запросов, попробуйте позже"

    already_exists: "⚠️ Ошибка: уже существует"
    undefined_command: "❓ Ошибка: неизвестная команда"
    undefined_interaction: "❓ Ошибка: неизвестное взаимодействие"
    undefined_callbackQuery: "❓ Ошибка: неизвестный запрос"

    invalid_hero_class: "❓ Ошибка: неизвестный класс героя"
    empty: "⚠️ Ошибка: пустое значение"
    too_long: "⚠️ Ошибка: значение слишком длинное, максимальное количество символов - %v"
