// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/telegram/handlers/helper.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	queries "github.com/arthurshafikov/tg-gladiator/internal/core/constants/queries"
	telegram "github.com/arthurshafikov/tg-gladiator/internal/core/constants/telegram"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
	gomock "github.com/golang/mock/gomock"
)

// MockTelegramHandlerHelper is a mock of TelegramHandlerHelper interface.
type MockTelegramHandlerHelper struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramHandlerHelperMockRecorder
}

// MockTelegramHandlerHelperMockRecorder is the mock recorder for MockTelegramHandlerHelper.
type MockTelegramHandlerHelperMockRecorder struct {
	mock *MockTelegramHandlerHelper
}

// NewMockTelegramHandlerHelper creates a new mock instance.
func NewMockTelegramHandlerHelper(ctrl *gomock.Controller) *MockTelegramHandlerHelper {
	mock := &MockTelegramHandlerHelper{ctrl: ctrl}
	mock.recorder = &MockTelegramHandlerHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramHandlerHelper) EXPECT() *MockTelegramHandlerHelperMockRecorder {
	return m.recorder
}

// AnswerCallbackQuery mocks base method.
func (m *MockTelegramHandlerHelper) AnswerCallbackQuery(callback tgbotapi.CallbackConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackQuery", callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackQuery indicates an expected call of AnswerCallbackQuery.
func (mr *MockTelegramHandlerHelperMockRecorder) AnswerCallbackQuery(callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackQuery", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).AnswerCallbackQuery), callback)
}

// AnswerCallbackQueryNil mocks base method.
func (m *MockTelegramHandlerHelper) AnswerCallbackQueryNil(queryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackQueryNil", queryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallbackQueryNil indicates an expected call of AnswerCallbackQueryNil.
func (mr *MockTelegramHandlerHelperMockRecorder) AnswerCallbackQueryNil(queryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackQueryNil", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).AnswerCallbackQueryNil), queryID)
}

// AnswerPreCheckoutQuery mocks base method.
func (m *MockTelegramHandlerHelper) AnswerPreCheckoutQuery(config tgbotapi.PreCheckoutConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerPreCheckoutQuery", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerPreCheckoutQuery indicates an expected call of AnswerPreCheckoutQuery.
func (mr *MockTelegramHandlerHelperMockRecorder) AnswerPreCheckoutQuery(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerPreCheckoutQuery", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).AnswerPreCheckoutQuery), config)
}

// CreateKeyboard mocks base method.
func (m *MockTelegramHandlerHelper) CreateKeyboard(buttons []telegram.KeyboardButton, perRow int) *tgbotapi.InlineKeyboardMarkup {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyboard", buttons, perRow)
	ret0, _ := ret[0].(*tgbotapi.InlineKeyboardMarkup)
	return ret0
}

// CreateKeyboard indicates an expected call of CreateKeyboard.
func (mr *MockTelegramHandlerHelperMockRecorder) CreateKeyboard(buttons, perRow interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyboard", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).CreateKeyboard), buttons, perRow)
}

// GetUpdatesChan mocks base method.
func (m *MockTelegramHandlerHelper) GetUpdatesChan(config tgbotapi.UpdateConfig) (tgbotapi.UpdatesChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan", config)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MockTelegramHandlerHelperMockRecorder) GetUpdatesChan(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).GetUpdatesChan), config)
}

// NewCallback mocks base method.
func (m *MockTelegramHandlerHelper) NewCallback(id, text string) tgbotapi.CallbackConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCallback", id, text)
	ret0, _ := ret[0].(tgbotapi.CallbackConfig)
	return ret0
}

// NewCallback indicates an expected call of NewCallback.
func (mr *MockTelegramHandlerHelperMockRecorder) NewCallback(id, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCallback", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewCallback), id, text)
}

// NewDeleteMessage mocks base method.
func (m *MockTelegramHandlerHelper) NewDeleteMessage(chatID int64, messageID int) tgbotapi.DeleteMessageConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteMessage", chatID, messageID)
	ret0, _ := ret[0].(tgbotapi.DeleteMessageConfig)
	return ret0
}

// NewDeleteMessage indicates an expected call of NewDeleteMessage.
func (mr *MockTelegramHandlerHelperMockRecorder) NewDeleteMessage(chatID, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteMessage", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewDeleteMessage), chatID, messageID)
}

// NewEditMessageReplyMarkup mocks base method.
func (m *MockTelegramHandlerHelper) NewEditMessageReplyMarkup(chatID int64, messageID int, replyMarkup *tgbotapi.InlineKeyboardMarkup) tgbotapi.EditMessageReplyMarkupConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEditMessageReplyMarkup", chatID, messageID, replyMarkup)
	ret0, _ := ret[0].(tgbotapi.EditMessageReplyMarkupConfig)
	return ret0
}

// NewEditMessageReplyMarkup indicates an expected call of NewEditMessageReplyMarkup.
func (mr *MockTelegramHandlerHelperMockRecorder) NewEditMessageReplyMarkup(chatID, messageID, replyMarkup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEditMessageReplyMarkup", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewEditMessageReplyMarkup), chatID, messageID, replyMarkup)
}

// NewEditMessageText mocks base method.
func (m *MockTelegramHandlerHelper) NewEditMessageText(chatID int64, messageID int, text string) tgbotapi.EditMessageTextConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEditMessageText", chatID, messageID, text)
	ret0, _ := ret[0].(tgbotapi.EditMessageTextConfig)
	return ret0
}

// NewEditMessageText indicates an expected call of NewEditMessageText.
func (mr *MockTelegramHandlerHelperMockRecorder) NewEditMessageText(chatID, messageID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEditMessageText", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewEditMessageText), chatID, messageID, text)
}

// NewMessage mocks base method.
func (m *MockTelegramHandlerHelper) NewMessage(chatID int64, text string) tgbotapi.MessageConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessage", chatID, text)
	ret0, _ := ret[0].(tgbotapi.MessageConfig)
	return ret0
}

// NewMessage indicates an expected call of NewMessage.
func (mr *MockTelegramHandlerHelperMockRecorder) NewMessage(chatID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessage", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewMessage), chatID, text)
}

// NewRow mocks base method.
func (m *MockTelegramHandlerHelper) NewRow(btnName string, query queries.Query) []tgbotapi.InlineKeyboardButton {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRow", btnName, query)
	ret0, _ := ret[0].([]tgbotapi.InlineKeyboardButton)
	return ret0
}

// NewRow indicates an expected call of NewRow.
func (mr *MockTelegramHandlerHelperMockRecorder) NewRow(btnName, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRow", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewRow), btnName, query)
}

// NewRowButton mocks base method.
func (m *MockTelegramHandlerHelper) NewRowButton(btnName string, query queries.Query) tgbotapi.InlineKeyboardButton {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRowButton", btnName, query)
	ret0, _ := ret[0].(tgbotapi.InlineKeyboardButton)
	return ret0
}

// NewRowButton indicates an expected call of NewRowButton.
func (mr *MockTelegramHandlerHelperMockRecorder) NewRowButton(btnName, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRowButton", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewRowButton), btnName, query)
}

// NewUpdateChannel mocks base method.
func (m *MockTelegramHandlerHelper) NewUpdateChannel(offset int) tgbotapi.UpdateConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUpdateChannel", offset)
	ret0, _ := ret[0].(tgbotapi.UpdateConfig)
	return ret0
}

// NewUpdateChannel indicates an expected call of NewUpdateChannel.
func (mr *MockTelegramHandlerHelperMockRecorder) NewUpdateChannel(offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUpdateChannel", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).NewUpdateChannel), offset)
}

// Send mocks base method.
func (m *MockTelegramHandlerHelper) Send(msg tgbotapi.Chattable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTelegramHandlerHelperMockRecorder) Send(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).Send), msg)
}

// SendInvoice mocks base method.
func (m *MockTelegramHandlerHelper) SendInvoice(msg tgbotapi.Chattable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvoice", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvoice indicates an expected call of SendInvoice.
func (mr *MockTelegramHandlerHelperMockRecorder) SendInvoice(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvoice", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).SendInvoice), msg)
}

// SendMessage mocks base method.
func (m *MockTelegramHandlerHelper) SendMessage(msg tgbotapi.MessageConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTelegramHandlerHelperMockRecorder) SendMessage(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).SendMessage), msg)
}

// SendMessageWithKeyboard mocks base method.
func (m *MockTelegramHandlerHelper) SendMessageWithKeyboard(msg tgbotapi.MessageConfig, replyCommands ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range replyCommands {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessageWithKeyboard", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageWithKeyboard indicates an expected call of SendMessageWithKeyboard.
func (mr *MockTelegramHandlerHelperMockRecorder) SendMessageWithKeyboard(msg interface{}, replyCommands ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, replyCommands...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageWithKeyboard", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).SendMessageWithKeyboard), varargs...)
}

// SendMessageWithoutKeyboard mocks base method.
func (m *MockTelegramHandlerHelper) SendMessageWithoutKeyboard(msg tgbotapi.MessageConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageWithoutKeyboard", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageWithoutKeyboard indicates an expected call of SendMessageWithoutKeyboard.
func (mr *MockTelegramHandlerHelperMockRecorder) SendMessageWithoutKeyboard(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageWithoutKeyboard", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).SendMessageWithoutKeyboard), msg)
}

// SendTextMessage mocks base method.
func (m *MockTelegramHandlerHelper) SendTextMessage(chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTextMessage", chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTextMessage indicates an expected call of SendTextMessage.
func (mr *MockTelegramHandlerHelperMockRecorder) SendTextMessage(chatID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTextMessage", reflect.TypeOf((*MockTelegramHandlerHelper)(nil).SendTextMessage), chatID, text)
}
