// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/services.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	interactions "github.com/arthurshafikov/tg-gladiator/internal/core/constants/interactions"
	models "github.com/arthurshafikov/tg-gladiator/internal/core/models"
	types "github.com/arthurshafikov/tg-gladiator/internal/core/types"
	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), args...)
}

// MockEventsHandler is a mock of EventsHandler interface.
type MockEventsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventsHandlerMockRecorder
}

// MockEventsHandlerMockRecorder is the mock recorder for MockEventsHandler.
type MockEventsHandlerMockRecorder struct {
	mock *MockEventsHandler
}

// NewMockEventsHandler creates a new mock instance.
func NewMockEventsHandler(ctrl *gomock.Controller) *MockEventsHandler {
	mock := &MockEventsHandler{ctrl: ctrl}
	mock.recorder = &MockEventsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsHandler) EXPECT() *MockEventsHandlerMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockEventsHandler) Dispatch(eventName string, params ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{eventName}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Dispatch", varargs...)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockEventsHandlerMockRecorder) Dispatch(eventName interface{}, params ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{eventName}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockEventsHandler)(nil).Dispatch), varargs...)
}

// MockChat is a mock of Chat interface.
type MockChat struct {
	ctrl     *gomock.Controller
	recorder *MockChatMockRecorder
}

// MockChatMockRecorder is the mock recorder for MockChat.
type MockChatMockRecorder struct {
	mock *MockChat
}

// NewMockChat creates a new mock instance.
func NewMockChat(ctrl *gomock.Controller) *MockChat {
	mock := &MockChat{ctrl: ctrl}
	mock.recorder = &MockChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChat) EXPECT() *MockChatMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockChat) Find(ctx context.Context, id int64) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockChatMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockChat)(nil).Find), ctx, id)
}

// FirstOrCreate mocks base method.
func (m *MockChat) FirstOrCreate(ctx context.Context, chat models.Chat) (*models.Chat, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreate", ctx, chat)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FirstOrCreate indicates an expected call of FirstOrCreate.
func (mr *MockChatMockRecorder) FirstOrCreate(ctx, chat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockChat)(nil).FirstOrCreate), ctx, chat)
}

// UpdateLatestActiveAt mocks base method.
func (m *MockChat) UpdateLatestActiveAt(ctx *types.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLatestActiveAt", ctx)
}

// UpdateLatestActiveAt indicates an expected call of UpdateLatestActiveAt.
func (mr *MockChatMockRecorder) UpdateLatestActiveAt(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLatestActiveAt", reflect.TypeOf((*MockChat)(nil).UpdateLatestActiveAt), ctx)
}

// UpdateUsername mocks base method.
func (m *MockChat) UpdateUsername(ctx *types.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername.
func (mr *MockChatMockRecorder) UpdateUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*MockChat)(nil).UpdateUsername), ctx, username)
}

// MockInteractions is a mock of Interactions interface.
type MockInteractions struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionsMockRecorder
}

// MockInteractionsMockRecorder is the mock recorder for MockInteractions.
type MockInteractionsMockRecorder struct {
	mock *MockInteractions
}

// NewMockInteractions creates a new mock instance.
func NewMockInteractions(ctrl *gomock.Controller) *MockInteractions {
	mock := &MockInteractions{ctrl: ctrl}
	mock.recorder = &MockInteractionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractions) EXPECT() *MockInteractionsMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockInteractions) Find(ctx *types.Context) (*interactions.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].(*interactions.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockInteractionsMockRecorder) Find(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockInteractions)(nil).Find), ctx)
}

// Remove mocks base method.
func (m *MockInteractions) Remove(ctx *types.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockInteractionsMockRecorder) Remove(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockInteractions)(nil).Remove), ctx)
}

// RemoveIfEquals mocks base method.
func (m *MockInteractions) RemoveIfEquals(ctx *types.Context, interaction *interactions.Interaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveIfEquals", ctx, interaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveIfEquals indicates an expected call of RemoveIfEquals.
func (mr *MockInteractionsMockRecorder) RemoveIfEquals(ctx, interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIfEquals", reflect.TypeOf((*MockInteractions)(nil).RemoveIfEquals), ctx, interaction)
}

// Set mocks base method.
func (m *MockInteractions) Set(ctx *types.Context, interaction interactions.Interaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, interaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockInteractionsMockRecorder) Set(ctx, interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockInteractions)(nil).Set), ctx, interaction)
}
